from flask_marshmallow import Marshmallow
from marshmallow import fields, validate

ma = Marshmallow()

class PropertySchema(ma.Schema):
    property_title = fields.Str(required=True, validate=validate.Length(min=5))
    price = fields.Float(required=True, validate=validate.Range(min=0))
    location = fields.Str(required=True)
    property_type = fields.Str(required=True)
    bedrooms = fields.Int(required=True, validate=validate.Range(min=0))
    bathrooms = fields.Int(required=True, validate=validate.Range(min=0))
    area_sqft = fields.Int(required=True, validate=validate.Range(min=1))
    # These are auto-generated by the backend
    listing_age = fields.Int(dump_only=True)
    views = fields.Int(dump_only=True)
    seller_id = fields.Str(dump_only=True)
    image_url = fields.Str(dump_only=True)